### ISSUE TITLE
Upgrading stable fails after 3.27 release

### ISSUE THREAD

**Issue by nielsenko** [pingbird/puro#100]
When trying to update to Flutter 3.27 I get the following crash:

```sh
puro upgrade stable --log-level=4
```

```
[D] PURO_FLUTTER_BIN: null
[V] Started waiting for lock on /Users/kasper/.puro/prefs.json
[V] Waiting for lock on /Users/kasper/.puro/prefs.json took 0ms
[D] target: PuroBuildTarget.macosX64
[D] Platform.executable: puro
[D] Platform.resolvedExecutable: /Users/kasper/.puro/bin/puro
[D] Platform.script: file:///Users/kasper/Projects/byolimit/treap/puro
[D] Platform.packageConfig: null
[D] No package root: Platform.packageConfig is null
[D] packageRoot: null
[D] executablePath: /Users/kasper/.puro/bin/puro
[D] scriptPath: /Users/kasper/.puro/bin/puro
[D] scriptExtension: 
[D] installationType: PuroInstallationType.distribution
[D] version: 1.4.6
[V] Checking if update is available
[V] Started waiting for lock on /Users/kasper/.puro/latest_version
[V] Waiting for lock on /Users/kasper/.puro/latest_version took 0ms
[D] lastNotification: null
[D] latestVersion: 1.4.6
[D] isOutOfDate: false
[D] willNotify: false
[D] shouldVersionCheck: false
[D] lastVersionCheck: 2024-12-11 16:56:08.717290
[V] Started waiting for lock on /Users/kasper/.puro/envs/stable/prefs.json
[V] Waiting for lock on /Users/kasper/.puro/envs/stable/prefs.json took 0ms
[V] Started waiting for lock on /Users/kasper/.puro/releases_macos.json
[V] Waiting for lock on /Users/kasper/.puro/releases_macos.json took 0ms
[V] Upgrading environment in /Users/kasper/.puro/envs/stable
[D] [git 72857] /Users/kasper/.puro/envs/stable/flutter> git rev-parse HEAD
[D] git: dec2ee5c1f98f8e84a7d5380c05eb8a3d0a81668
[D] [git 72857] finished with exit code 0 in 28ms
[D] [git 72858] /Users/kasper/.puro/envs/stable/flutter> git rev-parse --abbrev-ref HEAD
[D] git: stable
[D] [git 72858] finished with exit code 0 in 28ms
[V] Started waiting for lock on /Users/kasper/.puro/envs/stable/prefs.json
[V] Waiting for lock on /Users/kasper/.puro/envs/stable/prefs.json took 0ms
[V] Started waiting for lock on /Users/kasper/.puro/envs/stable/prefs.json
[V] Waiting for lock on /Users/kasper/.puro/envs/stable/prefs.json took 0ms
[V] Cloning flutter with shared refs
[D] repository: /Users/kasper/.puro/envs/stable/flutter
[D] flutterVersion: stable / 3.27.0 / 8495dee1fd
[D] forkRemoteUrl: stable / 3.27.0 / 8495dee1fd
[D] forkRef: null
[D] [git 72859] /Users/kasper/.puro/shared/flutter> git rev-parse --verify 8495dee1fd4aacbe9de707e7581203232f591b2f^{commit}
[D] git: 8495dee1fd4aacbe9de707e7581203232f591b2f
[D] [git 72859] finished with exit code 0 in 30ms
[V] Started initializing repository
[D] [git 72860] /Users/kasper/.puro/envs/stable/flutter> git remote -v
[D] git: origin	https://github.com/flutter/flutter.git (fetch)
[D] git: origin	https://github.com/flutter/flutter.git (push)
[D] [git 72860] finished with exit code 0 in 27ms
[V] Started checking out stable / 3.27.0 / 8495dee1fd
[D] [git 72861] /Users/kasper/.puro/envs/stable/flutter> git fetch --all
[D] git: fatal: bad object refs/remotes/origin/goderbauer-patch-1
[D] git: error: https://github.com/flutter/flutter.git did not send all necessary objects
[D] git: 
[D] [git 72861] finished with exit code 1 in 699ms
[V] git failed with exit code 1
[V] Checking out stable / 3.27.0 / 8495dee1fd took 728ms
[x] Bad state: git subprocess failed with exit code 1
    #0      GitClient._ensureSuccess (package:puro/src/git.dart:109)
    #1      GitClient.fetch (package:puro/src/git.dart:301)
    <asynchronous suspension>
    #2      cloneFlutterWithSharedRefs.<anonymous closure> (package:puro/src/env/create.dart:346)
    <asynchronous suspension>
    #3      ProgressNode.wrap (package:puro/src/progress.dart:68)
    <asynchronous suspension>
    #4      cloneFlutterWithSharedRefs (package:puro/src/env/create.dart:339)
    <asynchronous suspension>
    #5      upgradeEnvironment (package:puro/src/env/upgrade.dart:144)
    <asynchronous suspension>
    #6      CommandRunner.runCommand (package:args/command_runner.dart:212)
    <asynchronous suspension>
    #7      main (package:puro/src/cli.dart:256)
    <asynchronous suspension>
    
[x] Puro crashed! Please file an issue at https://github.com/pingbird/puro
```

Reported as requested, but I'm wondering if others get this issue as well?

**Comment by nielsenko** [comment]
If anyone experience the same issue, I managed to fix the issue by removing the stable environment, and reinstalling
```sh
puro rm stable -f
puro use -g stable
```

**Comment by pingbird** [comment]
> git: error: https://github.com/flutter/flutter.git did not send all necessary objects

Sounds like some kind of git cache corruption: https://github.com/flutter/flutter/issues/143788
