### ISSUE TITLE
404 on fetching engine version

### ISSUE THREAD

**Issue by nielsenko** [pingbird/puro#102]
```
puro use master
[E] Exception while Pre-caching engine
[E] HttpException: Error 404 from https://raw.githubusercontent.com/flutter/flutter/ba01bab4b8d85da260b289023e4a808577dea982/bin/internal/engine.version:
    404: Not Found
    #0      HttpException.ensureSuccess (package:puro/src/http.dart:196)
    #1      getEngineVersionOfCommit (package:puro/src/env/create.dart:60)
    <asynchronous suspension>
    #2      createEnvironment.<anonymous closure>.<anonymous closure> (package:puro/src/env/create.dart:128)
    <asynchronous suspension>
    #3      runOptional (package:puro/src/logger.dart:173)
    <asynchronous suspension>
    
[x] Flutter installation corrupt: Could not find engine version at /Users/kasper/.puro/envs/master/flutter/bin/internal/engine.version
    This can happen if `puro create` or `puro upgrade` was interrupted, try deleting the environment with `puro rm master
```
And yes, the url report 404. But the question is, why does it try to fetch that particular url, and why might it be missing.

I tried removing the `master` environment and then fetching it again:
```
puro rm -f master
puro use -g master
```
but I end in the situation above.

**Comment by pingbird** [comment]
Flutter is undergoing a merge of the engine and framework repos, master will be broken until that is finished

**Comment by pingbird** [comment]
Actually looks like that was finished a few days ago, I will update puro's engine commit locating code

**Comment by RandalSchwartz** [comment]
Came here to say "upgrade master" is also broken now:
```
Locohost.local:~ % puro upgrade master
[x] Flutter installation corrupt: Could not find engine version at /Users/merlyn/.puro/envs/master/flutter/bin/internal/engine.version
    This can happen if `puro create` or `puro upgrade` was interrupted, try deleting the environment with `puro rm master`

```

**Comment by pingbird** [comment]
Distracted by the holidays, sorry for the delay, it's a little more complicated than I thought.

**Comment by pingbird** [comment]
Should be fixed in 1.4.8

**Comment by nielsenko** [comment]
> Should be fixed in 1.4.8

I can confirm it is fixed on my end. Thank you for your effort - puro is such a great tool for managing flutter installs.

**Comment by RandalSchwartz** [comment]
LGTM as well... thanks!
