### ISSUE TITLE
Crashing on early versions tagged with v

### ISSUE THREAD

**Issue by fennelhans** [pingbird/puro#11]
```
puro create flutter118 1.1.8                                                                                                                         ﲵ zsh   100   4:54pm EST 
[x] FormatException: Could not parse "v1.1.8".
    #0      new Version.parse (package:pub_semver/src/version.dart:120)
    #1      FlutterVersion.query (package:puro/src/env/version.dart:129)
    <asynchronous suspension>
    #2      EnvCreateCommand.run (package:puro/src/commands/env_create.dart:55)
    <asynchronous suspension>
    #3      CommandRunner.runCommand (package:args/command_runner.dart:212)
    <asynchronous suspension>
    #4      main (package:puro/src/cli.dart:232)
    <asynchronous suspension>
    
[x] Puro crashed! Please file an issue at https://github.com/PixelToast/puro
    Consider running the command with a higher log level: `--log-level=4`
```

**Comment by PixelToast** [comment]
I fixed the version parsing issue but there are multiple things preventing this from working because of how the `dart` script was added to bin, stay tuned.

**Comment by pingbird** [comment]
Should be fixed in the next release of Puro, finally got it to run:

```
ping@bean:~/IdeaProjects/puro/puro$ puro -e flutter118 flutter --version
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ A new version of Flutter is available!                                     ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
  ╚════════════════════════════════════════════════════════════════════════════╝


Flutter 1.1.8 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 985ccb6d14 (4 years, 5 months ago) • 2019-01-08 13:45:55 -0800
Engine • revision 7112b72cc2
Tools • Dart 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)
```
