### ISSUE TITLE
`puro ls -p` throws when `.puro.json` is not found

### ISSUE THREAD

**Issue by passsy** [pingbird/puro#57]
```bash
$  puro ls -p
FileSystemException: Cannot resolve symbolic links, path = '/Users/pascal/Projects/some_project/engine/.puro.json' (OS Error: No such file or directory, errno = 2)
    #0      FileSystemEntity._throwIfError (dart:io/file_system_entity.dart:839)
    #1      FileSystemEntity.resolveSymbolicLinksSync (dart:io/file_system_entity.dart:358)
    #2      ForwardingFileSystemEntity.resolveSymbolicLinksSync (package:file/src/forwarding/forwarding_file_system_entity.dart:56)
    #3      FileExtensions.resolve (package:puro/src/extensions.dart:95)
    #4      cleanDotfiles.<anonymous closure> (package:puro/src/config.dart:767)
    #5      _updateGlobalPrefs.<anonymous closure> (package:puro/src/config.dart:709)
    #6      lockFile (package:puro/src/file_lock.dart:68)
    <asynchronous suspension>
    #7      updateGlobalPrefs (package:puro/src/config.dart:736)
    <asynchronous suspension>
    #8      getAllDotfiles (package:puro/src/config.dart:810)
    <asynchronous suspension>
    #9      listEnvironments (package:puro/src/env/list.dart:137)
    <asynchronous suspension>
    #10     CommandRunner.runCommand (package:args/command_runner.dart:212)
    <asynchronous suspension>
    #11     main (package:puro/src/cli.dart:248)
    <asynchronous suspension>
```

```
[i] Puro 1.4.1 (distribution/darwin-x64)
    Dart 3.1.3 (stable) (Tue Sep 26 14:25:13 2023 +0000) on "macos_x64"
```

**Comment by pingbird** [comment]
Should be fixed in 1.4.2, Thanks!
