### ISSUE TITLE
Puro failing to install environments on Windows when the user's home directory has a space

### ISSUE THREAD

**Issue by azwalzaman** [pingbird/puro#62]
```
[W] dart version check failed, deleting cache
[E] powershell: Expand-Archive : A positional parameter cannot be found that accepts argument
    'Name\.puro\shared\caches\22b600f240548c1cf6f5d3f9ae65a5c9e51bc443.zip'.
    At line:1 char:45
    + ... ll.Archive; Expand-Archive C:\Users\User Name\.puro\shared\caches ...
    +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : InvalidArgument: (:) [Expand-Archive], ParameterBindingException
        + FullyQualifiedErrorId : PositionalParameterNotFound,Expand-Archive
```

**Comment by pingbird** [comment]
to work around this install 7-zip and ensure it's in your PATH

**Comment by azwalzaman** [comment]
@pingbird So I did that but I get this error instead. I also confirmed that 7zip.exe was available in that terminal
```
[W] dart version check failed, deleting cache
[E] 7z.exe: 'C:\Program' is not recognized as an internal or external command,
    operable program or batch file.

[E] Exception while Pre-caching engine
[E] Assertion failed: "C:\\Program Files\\7-Zip\\7z.exe subprocess failed with exit code 1"
    #0      runProcess (package:puro/src/process.dart:110)
    <asynchronous suspension>
    #1      unzip (package:puro/src/env/engine.dart:140)
    <asynchronous suspension>
    #2      downloadSharedEngine.<anonymous closure> (package:puro/src/env/engine.dart:266)
    <asynchronous suspension>
    #3      ProgressNode.wrap (package:puro/src/progress.dart:68)
    <asynchronous suspension>
    #4      downloadSharedEngine (package:puro/src/env/engine.dart:264)
    <asynchronous suspension>
    #5      createEnvironment.<anonymous closure>.<anonymous closure> (package:puro/src/env/create.dart:136)
    <asynchronous suspension>
    #6      runOptional (package:puro/src/logger.dart:173)
    <asynchronous suspension>
    #7      createEnvironment.<anonymous closure> (package:puro/src/env/create.dart:165)
    <asynchronous suspension>
    #8      lockFile (package:puro/src/file_lock.dart:68)
    <asynchronous suspension>
    #9      createEnvironment (package:puro/src/env/create.dart:109)
    <asynchronous suspension>
    #10     CommandRunner.runCommand (package:args/command_runner.dart:212)
    <asynchronous suspension>
    #11     main (package:puro/src/cli.dart:256)
    <asynchronous suspension>

[W] dart version check failed, deleting cache
[E] 7z.exe: 'C:\Program' is not recognized as an internal or external command,
    operable program or batch file.

[x] Assertion failed: "C:\\Program Files\\7-Zip\\7z.exe subprocess failed with exit code 1"
    #0      runProcess (package:puro/src/process.dart:110)
    <asynchronous suspension>
    #1      unzip (package:puro/src/env/engine.dart:140)
    <asynchronous suspension>
    #2      downloadSharedEngine.<anonymous closure> (package:puro/src/env/engine.dart:266)
    <asynchronous suspension>
    #3      ProgressNode.wrap (package:puro/src/progress.dart:68)
    <asynchronous suspension>
    #4      downloadSharedEngine (package:puro/src/env/engine.dart:264)
    <asynchronous suspension>
    #5      setUpFlutterTool.<anonymous closure> (package:puro/src/env/flutter_tool.dart:114)
    <asynchronous suspension>
    #6      checkAtomic.<anonymous closure> (package:puro/src/file_lock.dart:234)
    <asynchronous suspension>
    #7      lockFile (package:puro/src/file_lock.dart:68)
    <asynchronous suspension>
    #8      checkAtomic (package:puro/src/file_lock.dart:232)
    <asynchronous suspension>
    #9      setUpFlutterTool (package:puro/src/env/flutter_tool.dart:108)
    <asynchronous suspension>
    #10     createEnvironment (package:puro/src/env/create.dart:181)
    <asynchronous suspension>
    #11     CommandRunner.runCommand (package:args/command_runner.dart:212)
    <asynchronous suspension>
    #12     main (package:puro/src/cli.dart:256)
    <asynchronous suspension>

[x] Puro crashed! Please file an issue at https://github.com/pingbird/puro
    Consider running the command with a higher log level: `--log-level=4`
```

**Comment by pingbird** [comment]
That's bizzare, its almost like all of the commands we send to Process.run are being sent through a shell

Is there anything not standard about your windows install or the environment these commands are running in?

**Comment by azwalzaman** [comment]
> That's bizzare, its almost like all of the commands we send to Process.run are being sent through a shell
> 
> Is there anything not standard about your windows install or the environment these commands are running in?

Nope. It's a standard Windows 11 Home installation and I'm using regular powershell not core anything

**Comment by pingbird** [comment]
I wasn't able to reproduce this on a Windows 11 machine unfortunately:
![Screenshot 2023-11-30 023522](https://github.com/pingbird/puro/assets/2466461/993b84f2-e18d-40e4-a616-163a6c0a8225)

There is definitely something really funky going on, maybe an antivirus? 🤔

**Comment by azwalzaman** [comment]
@pingbird The 7zip solution somehow works on another account :| Well, the one without 7zip works there too lol

**Comment by azwalzaman** [comment]
@pingbird So the 7zip solution worked on an account with no spaces in the name and failed on two accounts with spaces in the name. Could that be it somehow?

**Comment by pingbird** [comment]
A workaround has been pushed
