### ISSUE TITLE
Getting an error in setting up ide config

### ISSUE THREAD

**Issue by shashvat1965** [pingbird/puro#64]
puro use v3-10-5 --intellij 
```
[E] Exception while installing IntelliJ config
[E] Unsupported operation: Cannot extract a non-Windows file path from a file URI with an authority
    #0      _Uri._toFilePath (dart:core/uri.dart:2863)
    #1      _Uri.toFilePath (dart:core/uri.dart:2858)
    #2      IntelliJConfig.load (package:puro/src/workspace/intellij.dart:299)
    #3      installIdeConfigs.<anonymous closure> (package:puro/src/workspace/install.dart:31)
    #4      runOptional (package:puro/src/logger.dart:173)
    #5      installIdeConfigs (package:puro/src/workspace/install.dart:27)
    #6      installWorkspaceEnvironment.<anonymous closure> (package:puro/src/workspace/install.dart:122)
    #7      runOptional (package:puro/src/logger.dart:173)
    #8      installWorkspaceEnvironment (package:puro/src/workspace/install.dart:119)
    <asynchronous suspension>
    #9      switchEnvironment (package:puro/src/workspace/install.dart:154)
    <asynchronous suspension>
    #10     EnvUseCommand.run (package:puro/src/commands/env_use.dart:82)
    <asynchronous suspension>
    #11     CommandRunner.runCommand (package:args/command_runner.dart:212)
    <asynchronous suspension>
    #12     main (package:puro/src/cli.dart:256)
    <asynchronous suspension>

```
global command works only that intellij still uses the other version so I have to run applications from terminal still

**Comment by pingbird** [comment]
Should be fixed in 1.4.5
