### ISSUE TITLE
Issue with git worktrees

### ISSUE THREAD

**Issue by mselmanyildirim** [pingbird/puro#66]
I wanted to use different versions of `Flutter` in different [worktrees](https://git-scm.com/docs/git-worktree) of the same repository. I came across an error. I guess it's because `puro` wasn't able to write on `.git>info>exclude` file. I think it's not a road blocker for working of `puro`, but handling such errors may be more elegant.  
I use `PowerShell` on `Windows 10`. 
I got the error using ` Puro 1.4.4 (distribution/windows-x64)`
Issue trace is as follows, thanks for your efforts..

```
C:\path\to\my\worktree> puro use v3_13_2
[E] Exception while updating gitignore
[E] PathExistsException: Creation failed, path = 'C:\path\to\my\worktree\.git' (OS Error: Cannot create a file when that file already exists.
    , errno = 183)
    #0      _Directory.createSync (dart:io/directory_impl.dart:129)
    #1      _Directory.createSync (dart:io/directory_impl.dart:124)
    #2      _File.createSync (dart:io/file_impl.dart:303)
    #3      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:26)
    #4      updateConfigLines (package:puro/src/workspace/gitignore.dart:17)
    #5      updateGitignore (package:puro/src/workspace/gitignore.dart:61)
    #6      installWorkspaceEnvironment.<anonymous closure> (package:puro/src/workspace/install.dart:113)
    #7      runOptional (package:puro/src/logger.dart:173)
    #8      installWorkspaceEnvironment (package:puro/src/workspace/install.dart:110)
    #9      switchEnvironment (package:puro/src/workspace/install.dart:154)
    <asynchronous suspension>
    #10     EnvUseCommand.run (package:puro/src/commands/env_use.dart:83)
    <asynchronous suspension>
    #11     CommandRunner.runCommand (package:args/command_runner.dart:212)
    <asynchronous suspension>
    #12     main (package:puro/src/cli.dart:236)
    <asynchronous suspension>

[✓] Switched to environment `v3_13_2`
```

**Comment by pingbird** [comment]
This should be fixed in 1.4.5, sorry for the long wait!
