### ISSUE TITLE
[Windows]Install works, but can't create an env

### ISSUE THREAD

**Issue by johnwiese-ms** [pingbird/puro#72]
I have a brand new Windows 11 64bit install. I installed Git and VSCode and Puro (powershell).  When I try and do a `puro create stable` from an admin command prompt I get this:

C:\Windows\System32>puro create stable
[x] HandshakeException: Handshake error in client (OS Error:
        CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../third_party/boringssl/src/ssl/handshake.cc:393))
    #0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99)
    #1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:142)
    #2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:918)
    #3      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1047)
    <asynchronous suspension>
    #4      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:926)
    <asynchronous suspension>
    #5      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1047)
    <asynchronous suspension>

[x] Puro crashed! Please file an issue at https://github.com/pingbird/puro
    Consider running the command with a higher log level: `--log-level=4`

C:\Windows\System32>

if I just run Puro I get the normal help output.  Not sure what to do to get this working.

**Comment by pingbird** [comment]
This looks like an issue with your network which could be intercepting traffic, assuming this is some kind of corporate proxy you need to make sure the certificates are installed in your system properly

Also puro is not meant to be run as admin

**Comment by johnwiese-ms** [comment]
on a hotel wifi, but perhaps. I was also getting this at home the other day on my home network which has no proxy.

**Comment by johnwiese-ms** [comment]
looks like admin wasn't the issue, same from a non-elevated prompt

**Comment by johnwiese-ms** [comment]
and from my tmobile phone as a hotspot

**Comment by johnwiese-ms** [comment]
interesting, If I turn on my corporate VPN and try a puro create master it gets further:

C:\Users\jwiese>puro create master
[E] Exception while Pre-caching engine
[E] HandshakeException: Handshake error in client (OS Error:
        CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../third_party/boringssl/src/ssl/handshake.cc:393))
    #0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99)
    #1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:142)
    #2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:918)
    #3      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1047)
    <asynchronous suspension>

[W] dart version check failed, deleting cache
[x] HandshakeException: Handshake error in client (OS Error:
        CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../third_party/boringssl/src/ssl/handshake.cc:393))
    #0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99)
    #1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:142)
    #2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:918)
    #3      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1047)
    <asynchronous suspension>

[x] Puro crashed! Please file an issue at https://github.com/pingbird/puro
    Consider running the command with a higher log level: `--log-level=4`

C:\Users\jwiese>

**Comment by johnwiese-ms** [comment]
with logging:

C:\Users\jwiese>puro create stable --log-level=4
[D] PURO_FLUTTER_BIN: null
[V] Started waiting for lock on C:\Users\jwiese\.puro\prefs.json
[V] Waiting for lock on C:\Users\jwiese\.puro\prefs.json took 0ms
[D] target: PuroBuildTarget.windowsX64
[D] Platform.executable: puro
[D] Platform.resolvedExecutable: C:\Users\jwiese\.puro\bin\puro.exe
[D] Platform.script: file:///C:/Users/jwiese/puro
[D] Platform.packageConfig: null
[D] No package root: Platform.packageConfig is null
[D] packageRoot: null
[D] executablePath: c:\users\jwiese\.puro\bin\puro.exe
[D] scriptPath: c:\users\jwiese\.puro\bin\puro.exe
[D] scriptExtension: .exe
[D] installationType: PuroInstallationType.distribution
[D] version: 1.4.4
[V] Checking if update is available
[V] Started waiting for lock on C:\Users\jwiese\.puro\latest_version
[V] Waiting for lock on C:\Users\jwiese\.puro\latest_version took 0ms
[D] lastNotification: null
[D] latestVersion: 1.4.4
[D] isOutOfDate: false
[D] willNotify: false
[D] shouldVersionCheck: false
[D] lastVersionCheck: 2024-03-09 19:23:26.536352
[V] Started fetching https://storage.googleapis.com/flutter_infra_release/releases/releases_windows.json
[V] Fetching https://storage.googleapis.com/flutter_infra_release/releases/releases_windows.json took 172ms
[x] HandshakeException: Handshake error in client (OS Error:
        CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../third_party/boringssl/src/ssl/handshake.cc:393))
    #0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99)
    #1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:142)
    #2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:918)
    #3      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1047)
    <asynchronous suspension>
    #4      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:926)
    <asynchronous suspension>
    #5      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1047)
    <asynchronous suspension>

[x] Puro crashed! Please file an issue at https://github.com/pingbird/puro

C:\Users\jwiese>

**Comment by johnwiese-ms** [comment]
"you need to make sure the certificates are installed in your system properly"  

what certificates? from where?

**Comment by johnwiese-ms** [comment]
ok, so looks like either something resolved itself or there was something with the networks as you thought.  I am back home and now it's working, though this was not working on this network last week.  In any case, looks like I am back up and working now so closing this one.

**Comment by dilshadxahmad** [comment]
> ok, so looks like either something resolved itself or there was something with the networks as you thought. I am back home and now it's working, though this was not working on this network last week. In any case, looks like I am back up and working now so closing this one.

Looks like we are the only two people, who encountered this issue. 🙏
