### ISSUE TITLE
Puro crashed

### ISSUE THREAD

**Issue by LaPyaeOo** [pingbird/puro#83]
*Error reproduced*

``` puro create change_new_environment 3.16.0 ```

*Error logs*

```[W] dart version check failed, deleting cache
[E] git: Cloning into '/Users/myStorage/.puro/shared/flutter'...
    remote: Enumerating objects: 513958, done.        
    remote: Counting objects:   3% (1/28)        
    remote: Counting objects:   7% (2/28)        
    remote: Counting objects:  10% (3/28)        
    remote: Counting objects:  14% (4/28)        
    remote: Counting objects:  17% (5/28)        
    remote: Counting objects:  21% (6/28)        
    remote: Counting objects:  25% (7/28)        
    remote: Counting objects:  28% (8/28)        
    remote: Counting objects:  32% (9/28)        
    remote: Counting objects:  35% (10/28)        
    remote: Counting objects:  39% (11/28)        
    remote: Counting objects:  42% (12/28)        
    remote: Counting objects:  46% (13/28)        
    remote: Counting objects:  50% (14/28)        
    remote: Counting objects:  53% (15/28)        
    remote: Counting objects:  57% (16/28)        
    remote: Counting objects:  60% (17/28)        
    remote: Counting objects:  64% (18/28)        
    remote: Counting objects:  67% (19/28)        
    remote: Counting objects:  71% (20/28)        
    remote: Counting objects:  75% (21/28)        
    remote: Counting objects:  78% (22/28)        
    remote: Counting objects:  82% (23/28)        
    remote: Counting objects:  85% (24/28)        
    remote: Counting objects:  89% (25/28)        
    remote: Counting objects:  92% (26/28)        
    remote: Counting objects:  96% (27/28)        
    remote: Counting objects: 100% (28/28)        
    remote: Counting objects: 100% (28/28), done.        
    remote: Compressing objects:   5% (1/17)        
    remote: Compressing objects:  11% (2/17)        
    remote: Compressing objects:  17% (3/17)        
    remote: Compressing objects:  23% (4/17)        
    remote: Compressing objects:  29% (5/17)        
    remote: Compressing objects:  35% (6/17)        
    remote: Compressing objects:  41% (7/17)        
    remote: Compressing objects:  47% (8/17)        
    remote: Compressing objects:  52% (9/17)        
    remote: Compressing objects:  58% (10/17)        
    remote: Compressing objects:  64% (11/17)        
    remote: Compressing objects:  70% (12/17)        
    remote: Compressing objects:  76% (13/17)        
    remote: Compressing objects:  82% (14/17)        
    remote: Compressing objects:  88% (15/17)        
    remote: Compressing objects:  94% (16/17)        
    remote: Compressing objects: 100% (17/17)        
    remote: Compressing objects: 100% (17/17), done.        
    Receiving objects:   0% (1/513958)
    Receiving objects:   0% (72/513958), 52.01 KiB | 58.00 KiB/s
    Receiving objects:   0% (164/513958), 164.01 KiB | 87.00 KiB/s
    Receiving objects:   0% (235/513958), 284.01 KiB | 90.00 KiB/s
    Receiving objects:   0% (318/513958), 380.01 KiB | 85.00 KiB/s
    Receiving objects:   0% (358/513958), 428.01 KiB | 81.00 KiB/s
    Receiving objects:   0% (428/513958), 468.01 KiB | 78.00 KiB/s
    Receiving objects:   0% (506/513958), 596.01 KiB | 81.00 KiB/s
    Receiving objects:   0% (554/513958), 620.01 KiB | 76.00 KiB/s
    Receiving objects:   0% (599/513958), 708.01 KiB | 70.00 KiB/s
    Receiving objects:   0% (704/513958), 836.01 KiB | 75.00 KiB/s
    Receiving objects:   0% (760/513958), 884.01 KiB | 78.00 KiB/s
    Receiving objects:   0% (803/513958), 948.01 KiB | 80.00 KiB/s
    Receiving objects:   0% (932/513958), 1.07 MiB | 88.00 KiB/s  
    Receiving objects:   0% (1096/513958), 1.25 MiB | 108.00 KiB/s
    Receiving objects:   0% (1232/513958), 1.46 MiB | 127.00 KiB/s
    Receiving objects:   0% (1322/513958), 1.54 MiB | 136.00 KiB/s
    Receiving objects:   0% (1396/513958), 1.61 MiB | 141.00 KiB/s
    Receiving objects:   0% (1458/513958), 1.73 MiB | 129.00 KiB/s
    Receiving objects:   0% (1541/513958), 1.81 MiB | 126.00 KiB/s
    Receiving objects:   0% (1633/513958), 1.90 MiB | 103.00 KiB/s
    Receiving objects:   0% (1751/513958), 2.05 MiB | 101.00 KiB/s
    Receiving objects:   0% (1825/513958), 2.14 MiB | 105.00 KiB/s
    Receiving objects:   0% (1938/513958), 2.30 MiB | 115.00 KiB/s
    Receiving objects:   0% (2041/513958), 2.37 MiB | 116.00 KiB/s
    Receiving objects:   0% (2124/513958), 2.48 MiB | 119.00 KiB/s
    Receiving objects:   0% (2195/513958), 2.60 MiB | 106.00 KiB/s
    Receiving objects:   0% (2342/513958), 2.68 MiB | 113.00 KiB/s
    Receiving objects:   0% (2466/513958), 2.83 MiB | 114.00 KiB/s
    Receiving objects:   0% (2570/513958), 2.90 MiB | 108.00 KiB/s
    Receiving objects:   0% (2635/513958), 2.96 MiB | 77.00 KiB/s 
    Receiving objects:   0% (2710/513958), 3.03 MiB | 68.00 KiB/s
    Receiving objects:   0% (2721/513958), 3.03 MiB | 68.00 KiB/s
    Receiving objects:   0% (2826/513958), 3.12 MiB | 51.00 KiB/s
    Receiving objects:   0% (2902/513958), 3.12 MiB | 51.00 KiB/s
    Receiving objects:   0% (3059/513958), 3.29 MiB | 49.00 KiB/s
    Receiving objects:   0% (3157/513958), 3.36 MiB | 44.00 KiB/s
    Receiving objects:   0% (3214/513958), 3.39 MiB | 42.00 KiB/s
    Receiving objects:   0% (3333/513958), 3.49 MiB | 57.00 KiB/s
    Receiving objects:   0% (3448/513958), 3.54 MiB | 57.00 KiB/s
    Receiving objects:   0% (3530/513958), 3.63 MiB | 78.00 KiB/s
    Receiving objects:   0% (3662/513958), 3.72 MiB | 73.00 KiB/s
    Receiving objects:   0% (3772/513958), 3.80 MiB | 76.00 KiB/s
    Receiving objects:   0% (3862/513958), 3.85 MiB | 75.00 KiB/s
    Receiving objects:   0% (4034/513958), 3.98 MiB | 85.00 KiB/s
    Receiving objects:   0% (4230/513958), 4.05 MiB | 94.00 KiB/s
    Receiving objects:   0% (4385/513958), 4.20 MiB | 105.00 KiB/s
    Receiving objects:   0% (4537/513958), 4.32 MiB | 109.00 KiB/s
    Receiving objects:   0% (4694/513958), 4.46 MiB | 123.00 KiB/s
    Receiving objects:   0% (4798/513958), 4.50 MiB | 119.00 KiB/s
    Receiving objects:   0% (4974/513958), 4.61 MiB | 113.00 KiB/s
    Receiving objects:   0% (5133/513958), 4.77 MiB | 112.00 KiB/s
    Receiving objects:   1% (5140/513958), 4.77 MiB | 112.00 KiB/s
    Receiving objects:   1% (5288/513958), 4.89 MiB | 113.00 KiB/s
    Receiving objects:   1% (5472/513958), 4.95 MiB | 108.00 KiB/s
    Receiving objects:   1% (5696/513958), 5.13 MiB | 125.00 KiB/s
    Receiving objects:   1% (5792/513958), 5.25 MiB | 121.00 KiB/s
    Receiving objects:   1% (5837/513958), 5.28 MiB | 106.00 KiB/s
    Receiving objects:   1% (5896/513958), 5.31 MiB | 96.00 KiB/s 
    Receiving objects:   1% (5976/513958), 5.39 MiB | 87.00 KiB/s
    Receiving objects:   1% (6044/513958), 5.45 MiB | 69.00 KiB/s
    Receiving objects:   1% (6188/513958), 5.55 MiB | 58.00 KiB/s
    Receiving objects:   1% (6301/513958), 5.62 MiB | 65.00 KiB/s
    Receiving objects:   1% (6443/513958), 5.74 MiB | 76.00 KiB/s
    Receiving objects:   1% (6526/513958), 5.79 MiB | 82.00 KiB/s
    Receiving objects:   1% (6656/513958), 5.84 MiB | 80.00 KiB/s
    Receiving objects:   1% (6816/513958), 5.96 MiB | 93.00 KiB/s
    Receiving objects:   1% (6956/513958), 6.11 MiB | 97.00 KiB/s
    Receiving objects:   1% (7124/513958), 6.17 MiB | 95.00 KiB/s
    Receiving objects:   1% (7318/513958), 6.32 MiB | 106.00 KiB/s
    Receiving objects:   1% (7503/513958), 6.42 MiB | 111.00 KiB/s
    Receiving objects:   1% (7717/513958), 6.52 MiB | 110.00 KiB/s
    Receiving objects:   1% (7901/513958), 6.66 MiB | 118.00 KiB/s
    Receiving objects:   1% (7964/513958), 6.74 MiB | 108.00 KiB/s
    Receiving objects:   1% (8130/513958), 6.82 MiB | 106.00 KiB/s
    Receiving objects:   1% (8219/513958), 6.92 MiB | 96.00 KiB/s 
    Receiving objects:   1% (8365/513958), 6.96 MiB | 95.00 KiB/s
    Receiving objects:   1% (8531/513958), 7.10 MiB | 95.00 KiB/s
    Receiving objects:   1% (8659/513958), 7.20 MiB | 95.00 KiB/s
    Receiving objects:   1% (8705/513958), 7.25 MiB | 75.00 KiB/s
    Receiving objects:   1% (8737/513958), 7.28 MiB | 59.00 KiB/s
    Receiving objects:   1% (8762/513958), 7.29 MiB | 55.00 KiB/s
    Receiving objects:   1% (8807/513958), 7.31 MiB | 51.00 KiB/s
    Receiving objects:   1% (8967/513958), 7.43 MiB | 50.00 KiB/s
    Receiving objects:   1% (8992/513958), 7.43 MiB | 42.00 KiB/s
    Receiving objects:   1% (9154/513958), 7.50 MiB | 39.00 KiB/s
    Receiving objects:   1% (9340/513958), 7.65 MiB | 71.00 KiB/s
    Receiving objects:   1% (9435/513958), 7.69 MiB | 73.00 KiB/s
    Receiving objects:   1% (9512/513958), 7.77 MiB | 73.00 KiB/s
    Receiving objects:   1% (9637/513958), 7.81 MiB | 71.00 KiB/s
    Receiving objects:   1% (9771/513958), 7.91 MiB | 81.00 KiB/s
    Receiving objects:   1% (9974/513958), 8.04 MiB | 77.00 KiB/s
    Receiving objects:   1% (10096/513958), 8.11 MiB | 74.00 KiB/s
    Receiving objects:   1% (10192/513958), 8.11 MiB | 74.00 KiB/s
    Receiving objects:   2% (10280/513958), 8.19 MiB | 80.00 KiB/s
    Receiving objects:   2% (10339/513958), 8.25 MiB | 80.00 KiB/s
    Receiving objects:   2% (10461/513958), 8.28 MiB | 79.00 KiB/s
    Receiving objects:   2% (10607/513958), 8.38 MiB | 75.00 KiB/s
    Receiving objects:   2% (10687/513958), 8.45 MiB | 67.00 KiB/s
    Receiving objects:   2% (10809/513958), 8.49 MiB | 72.00 KiB/s
    Receiving objects:   2% (10943/513958), 8.60 MiB | 70.00 KiB/s
    Receiving objects:   2% (11117/513958), 8.64 MiB | 73.00 KiB/s
    Receiving objects:   2% (11198/513958), 8.75 MiB | 72.00 KiB/s
    Receiving objects:   2% (11266/513958), 8.79 MiB | 66.00 KiB/s
    Receiving objects:   2% (11402/513958), 8.84 MiB | 70.00 KiB/s
    Receiving objects:   2% (11564/513958), 8.93 MiB | 77.00 KiB/s
    Receiving objects:   2% (11752/513958), 9.06 MiB | 82.00 KiB/s
    Receiving objects:   2% (11927/513958), 9.17 MiB | 84.00 KiB/s
    Receiving objects:   2% (11996/513958), 9.18 MiB | 78.00 KiB/s
    Receiving objects:   2% (12090/513958), 9.25 MiB | 83.00 KiB/s
    Receiving objects:   2% (12220/513958), 9.30 MiB | 76.00 KiB/s
    Receiving objects:   2% (12366/513958), 9.43 MiB | 76.00 KiB/s
    Receiving objects:   2% (12446/513958), 9.47 MiB | 63.00 KiB/s
    Receiving objects:   2% (12562/513958), 9.54 MiB | 70.00 KiB/s
    Receiving objects:   2% (12766/513958), 9.61 MiB | 68.00 KiB/s
    Receiving objects:   2% (12931/513958), 9.70 MiB | 74.00 KiB/s
    Receiving objects:   2% (13121/513958), 9.87 MiB | 89.00 KiB/s
    Receiving objects:   2% (13258/513958), 9.93 MiB | 89.00 KiB/s
    Receiving objects:   2% (13392/513958), 10.03 MiB | 95.00 KiB/s
    Receiving objects:   2% (13442/513958), 10.06 MiB | 87.00 KiB/s
    Receiving objects:   2% (13534/513958), 10.11 MiB | 81.00 KiB/s
    Receiving objects:   2% (13734/513958), 10.23 MiB | 87.00 KiB/s
    Receiving objects:   2% (13872/513958), 10.26 MiB | 73.00 KiB/s
    Receiving objects:   2% (13951/513958), 10.36 MiB | 62.00 KiB/s
    Receiving objects:   2% (13979/513958), 10.36 MiB | 62.00 KiB/s
    Receiving objects:   2% (14156/513958), 10.44 MiB | 66.00 KiB/s
    Receiving objects:   2% (14249/513958), 10.53 MiB | 70.00 KiB/s
    Receiving objects:   2% (14383/513958), 10.57 MiB | 66.00 KiB/s
    Receiving objects:   2% (14460/513958), 10.65 MiB | 63.00 KiB/s
    Receiving objects:   2% (14543/513958), 10.68 MiB | 59.00 KiB/s
    Receiving objects:   2% (14608/513958), 10.74 MiB | 54.00 KiB/s
    Receiving objects:   2% (14613/513958), 10.75 MiB | 50.00 KiB/s
    Receiving objects:   2% (14667/513958), 10.79 MiB | 47.00 KiB/s
    Receiving objects:   2% (14719/513958), 10.82 MiB | 36.00 KiB/s
    Receiving objects:   2% (14802/513958), 10.82 MiB | 36.00 KiB/s
    Receiving objects:   2% (14925/513958), 10.91 MiB | 38.00 KiB/s
    Receiving objects:   2% (14965/513958), 10.96 MiB | 32.00 KiB/s
    Receiving objects:   2% (15167/513958), 11.07 MiB | 45.00 KiB/s
    Receiving objects:   3% (15419/513958), 11.15 MiB | 55.00 KiB/s
    Receiving objects:   3% (15467/513958), 11.25 MiB | 65.00 KiB/s
    Receiving objects:   3% (15640/513958), 11.32 MiB | 73.00 KiB/s
    Receiving objects:   3% (15785/513958), 11.43 MiB | 85.00 KiB/s
    Receiving objects:   3% (15997/513958), 11.56 MiB | 93.00 KiB/s
    Receiving objects:   3% (16226/513958), 11.64 MiB | 129.00 KiB/s
    Receiving objects:   3% (16292/513958), 11.73 MiB | 98.00 KiB/s 
    Receiving objects:   3% (16427/513958), 11.81 MiB | 94.00 KiB/s
    Receiving objects:   3% (16506/513958), 11.86 MiB | 87.00 KiB/s
    Receiving objects:   3% (16629/513958), 11.91 MiB | 90.00 KiB/s
    Receiving objects:   3% (16735/513958), 11.97 MiB | 76.00 KiB/s
    Receiving objects:   3% (16815/513958), 12.01 MiB | 71.00 KiB/s
    Receiving objects:   3% (16923/513958), 12.10 MiB | 65.00 KiB/s
    Receiving objects:   3% (17033/513958), 12.14 MiB | 61.00 KiB/s
    Receiving objects:   3% (17170/513958), 12.24 MiB | 62.00 KiB/s
    Receiving objects:   3% (17238/513958), 12.27 MiB | 59.00 KiB/s
    Receiving objects:   3% (17387/513958), 12.34 MiB | 62.00 KiB/s
    Receiving objects:   3% (17478/513958), 12.42 MiB | 63.00 KiB/s
    error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
    error: 365 bytes of body are still expected
    fetch-pack: unexpected disconnect while reading sideband packet
    fatal: early EOF
    fatal: fetch-pack: invalid index-pack output
[=              ] Downloading engine
[x] Bad state: git subprocess failed with exit code 128
    #0      GitClient._ensureSuccess (package:puro/src/git.dart:109)
    #1      GitClient.clone (package:puro/src/git.dart:167)
    <asynchronous suspension>
    #2      GitClient.cloneWithProgress.<anonymous closure> (package:puro/src/git.dart:181)
    <asynchronous suspension>
    #3      ProgressNode.wrap (package:puro/src/progress.dart:68)
    <asynchronous suspension>
    #4      GitClient.cloneWithProgress (package:puro/src/git.dart:179)
    <asynchronous suspension>
    #5      fetchOrCloneShared (package:puro/src/env/create.dart:205)
    <asynchronous suspension>
    #6      cloneFlutterWithSharedRefs (package:puro/src/env/create.dart:332)
    <asynchronous suspension>
    #7      createEnvironment.<anonymous closure> (package:puro/src/env/create.dart:148)
    <asynchronous suspension>
    #8      lockFile (package:puro/src/file_lock.dart:68)
    <asynchronous suspension>
    #9      createEnvironment (package:puro/src/env/create.dart:109)
    <asynchronous suspension>
    #10     CommandRunner.runCommand (package:args/command_runner.dart:212)
    <asynchronous suspension>
    #11     main (package:puro/src/cli.dart:256)
    <asynchronous suspension>
    
[x] Puro crashed! Please file an issue at https://github.com/pingbird/puro
    Consider running the command with a higher log level: `--log-level=4`
```

After I have downloaded **puro**  and immediately download the flutter version which I want to use. But I face with this error.

**Comment by pingbird** [comment]
There are widespread reports of GitHub servers having connection problems, this doesn't appear to be an issue with puro.

**Comment by LaPyaeOo** [comment]
> There are widespread reports of GitHub servers having connection problems, this doesn't appear to be an issue with puro.

Yes... sorry for reporting as issue. It is related with vpn issue.
