### ISSUE TITLE
Exception while Syncing flutter cache

### ISSUE THREAD

**Issue by nielsenko** [pingbird/puro#87]
Using a github action windows runner, against a newly restored cache of the $PURO_ROOT folder, I get this exception on the first `puro` command:
```
[E] Exception while Syncing flutter cache
[E] PathExistsException: Cannot create link, path = 'D:\a\realm-dart\puro\envs\stable\flutter\bin\cache\artifacts' (OS Error: Cannot create a file when that file already exists.
    , errno = 183)
    #0      _Link.throwIfError (dart:io/link.dart:339)
    #1      _Link.createSync (dart:io/link.dart:267)
    #2      ForwardingLink.createSync (package:file/src/forwarding/forwarding_link.dart:20)
    #3      createLinks (package:puro/src/file_lock.dart:301)
    #4      syncFlutterCache (package:puro/src/env/engine.dart:399)
    <asynchronous suspension>
    #5      trySyncFlutterCache.<anonymous closure> (package:puro/src/env/engine.dart:407)
    <asynchronous suspension>
    #6      runOptional (package:puro/src/logger.dart:173)
    <asynchronous suspension>
    #7      trySyncFlutterCache (package:puro/src/env/engine.dart:406)
    <asynchronous suspension>
    #8      runFlutterCommand (package:puro/src/env/command.dart:45)
    <asynchronous suspension>
    #9      PubCommand.run (package:puro/src/commands/pub.dart:26)
    <asynchronous suspension>
    #10     CommandRunner.runCommand (package:args/command_runner.dart:212)
    <asynchronous suspension>
    #11     main (package:puro/src/cli.dart:256)
    <asynchronous suspension>
```
The actual command was: `puro pub global run melos bootstrap`, but I don't think that is important. The same github action works fine on both linux, and macos.

The important part is that the cache of `$PURO_ROOT` has been restored. If I skip that step, and hence puro is working against a clean slate then the issue doesn't occur.

To be honest I'm not fully confident that this is the right place to raise this issue, but given that the stack-trace starts in puro I'll start here.

If it has any relevance, the exacts action is: https://github.com/realm/realm-dart/blob/kn/setup-runner-ci-action/.github/actions/setup-runner/action.yml and a failed run can be seen here: https://github.com/realm/realm-dart/actions/runs/9385985556/job/25845570110#step:6:82

**Comment by pingbird** [comment]
I think the problem is that actions/cache is not preserving symlinks which breaks puro's own caching mechanism

The error you saw is just a warning, but I've added PURO_SKIP_CACHE_SYNC / --skip-cache-sync to the next release which should hide it
